### ISSUE TITLE
ERROR:  pgvecto.rs: IPC connection is closed unexpected. v0.2.0

### ISSUE THREAD

**Issue by reefland** [tensorchord/pgvecto.rs#409]
Attempted Immich `v1.94.1` to `v1.97.0` with cloudnative-pg operator with postgres: `ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.2-v0.2.0`, having similar issue as <https://github.com/immich-app/immich/issues/7327>

Upgrade instructions fail at the end:
```
immich=# CREATE SCHEMA IF NOT EXISTS vectors;
CREATE SCHEMA
immich=# ALTER DATABASE immich SET search_path TO "$user", public, vectors;
ALTER DATABASE
immich=# SET search_path TO "$user", public, vectors;
SET
immich=# UPDATE pg_catalog.pg_extension SET extversion = '0.1.11' WHERE extname = 'vectors';
UPDATE 1
immich=# UPDATE pg_catalog.pg_extension SET extrelocatable = true WHERE extname = 'vectors';
UPDATE 1
immich=# ALTER EXTENSION vectors SET SCHEMA vectors;
ALTER EXTENSION
immich=# UPDATE pg_catalog.pg_extension SET extrelocatable = false WHERE extname = 'vectors';
UPDATE 1
immich=# ALTER EXTENSION vectors UPDATE TO '0.2.0';
ALTER EXTENSION
immich=# SELECT pgvectors_upgrade();
ERROR:  pgvecto.rs: IPC connection is closed unexpected.
ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
```

```
immich=# \dx
List of installed extensions
Name      | Version |   Schema   |                                         Description
---------------+---------+------------+----------------------------------------------------------------------------------------------
cube          | 1.5     | public     | data type for multidimensional cubes
earthdistance | 1.1     | public     | calculate great-circle distances on the surface of the Earth
plpgsql       | 1.0     | pg_catalog | PL/pgSQL procedural language
uuid-ossp     | 1.1     | public     | generate universally unique identifiers (UUIDs)
vectors       | 0.2.0   | vectors    | vectors: Vector database plugin for Postgres, written in Rust, specifically designed for LLM
```

immich-server:
```
[Nest] 7 - 03/05/2024, 2:22:19 AM LOG [CommunicationRepository] Initialized websocket server
[Nest] 7 - 03/05/2024, 2:22:30 AM WARN [DatabaseService] Could not run vector reindexing checks. If the extension was updated, please restart the Postgres instance.
/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
^
QueryFailedError: pgvecto.rs: IPC connection is closed unexpected.
```

Tried restarting the cluster multiple times. No improvement. After restart, PostgreSQL logs show:
```
UTC","user_name":"app","database_name":"immich","process_id":"6255","connection_from":"10.42.1.63:54128","session_id":"65e68f51.186f","session_line_num":"1","command_tag":"SELECT","session_start_time":"2024-03-05 03:19:45 UTC","virtual_transaction_id":"9/8","transaction_id":"0","error_severity":"ERROR","sql_state_code":"XX000","message":"called `Result::unwrap()` on an `Err` value: NoSuchType(\"vectors.vector_index_stat\")","query":"\n SELECT idx_status\n FROM pg_vector_index_stat\n WHERE indexname = $1","backend_type":"client backend","query_id":"0"}}
```

Anytime I try to run `SELECT pgvectors_upgrade();`, I'm getting:
```
ERROR:  pgvecto.rs: IPC connection is closed unexpected.
ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
```

I considered the following to reinstall vectors:
```
# \c immich
DROP EXTENSION vectors;
```

But decided not to with this message:
```
ERROR:  cannot drop extension vectors because other objects depend on it
DETAIL:  column embedding of table asset_faces depends on type vector
column embedding of table smart_search depends on type vector
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

More digging let me to this repo: <https://github.com/tensorchord/pgvecto.rs/issues/376#issuecomment-1960701731> So I tried this:
```
immich=# DELETE FROM smart_search WHERE true;
DELETE 3634
immich=# DELETE FROM asset_faces WHERE true;
DELETE 954
immich=# SET vectors.pgvector_compatibility=on;
SET
immich=# CREATE INDEX IF NOT EXISTS clip_index ON smart_search
USING hnsw (embedding vector_cosine_ops)
WITH (ef_construction = 300, m = 16);
NOTICE:  relation "clip_index" already exists, skipping
CREATE INDEX
immich=# CREATE INDEX IF NOT EXISTS face_index ON asset_faces
USING hnsw (embedding vector_cosine_ops)
WITH (ef_construction = 300, m = 16);
NOTICE:  relation "face_index" already exists, skipping
CREATE INDEX
```

And notice I started midway, so saw the drop extension I was going to try, but it failed:
```
postgres=# \c immich
immich=# DROP EXTENSION IF EXISTS vectors CASCADE;
NOTICE:  drop cascades to 2 other objects
DETAIL:  drop cascades to column embedding of table asset_faces
drop cascades to column embedding of table smart_search
ERROR:  pgvecto.rs: IPC connection is closed unexpected.
ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
```

And I give up.  I see that `v0.2.1` is related, but has not trickled to images yet.

**Comment by VoVAllen** [comment]
Sorry for the problem. This is likely due to the problem of NULL vector in the index which we fixed in 0.2.1. Another way to reset pgvecto.rs is to manually delete all the file under `pgdata/pg_vectors`. This will remove all the indexes there. Your data is in the postgres storage and won't be affected. Only indexes are deleted by this way. Then everything should work. You only need to do the `REINDEX` on all the vector columns

**Comment by reefland** [comment]
I saw `v0.2.1` was available this morning: `ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.2-v0.2.1`.  Upgraded to that:
```
postgres=# \c immich
You are now connected to database "immich" as user "postgres".

immich=# SELECT pgvectors_upgrade();
WARNING:  pgvecto.rs is upgraded. Restart PostgreSQL to take effects.
pgvectors_upgrade
-------------------

(1 row)
```
```
$ kubectl cnpg restart postgres16 -n cloudnative-pg
postgres16 restarted
```

 I restarted it 2 more times.  This is still postgres:
```
UTC","user_name":"app","database_name":"immich","process_id":"5399","connection_from":"10.42.4.226:39502","session_id":"65e71836.1517","session_line_num":"1","command_tag":"SELECT","session_start_time":"2024-03-05 13:03:50 UTC","virtual_transaction_id":"9/28","transaction_id":"0","error_severity":"ERROR","sql_state_code":"XX000","message":"called `Result::unwrap()` on an `Err` value: NoSuchType(\"vectors.vector_index_stat\")","query":"\n SELECT idx_status\n FROM pg_vector_index_stat\n WHERE indexname = $1","backend_type":"client backend","query_id":"0"}}
```
Immich, still crash looping on this:
```
[Nest] 7 - 03/05/2024, 1:07:15 PM WARN [DatabaseService] Could not run vector reindexing checks. If the extension was updated, please restart the Postgres instance.
/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
^
QueryFailedError: called `Result::unwrap()` on an `Err` value: NoSuchType("vectors.vector_index_stat")
at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async DataSource.query (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:350:20)
at async DatabaseRepository.shouldReindex (/usr/src/app/dist/infra/repositories/database.repository.js:127:25)
at async /usr/src/app/dist/domain/database/database.service.js:41:21
at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23 {
query: '\n' +
' SELECT idx_status\n' +
' FROM pg_vector_index_stat\n' +
' WHERE indexname = $1',
parameters: [ 'clip_index' ],
driverError: error: called `Result::unwrap()` on an `Err` value: NoSuchType("vectors.vector_index_stat")
at /usr/src/app/node_modules/pg/lib/client.js:526:17
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
at async DataSource.query (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:350:20)
at async DatabaseRepository.shouldReindex (/usr/src/app/dist/infra/repositories/database.repository.js:127:25)
at async /usr/src/app/dist/domain/database/database.service.js:41:21
at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23 {
```

Not sure what to try next.

**Comment by reefland** [comment]
hmm...  seems `reindex database;` did the trick.
```
immich=# \dx
List of installed extensions
Name      | Version |   Schema   |                                         Description
---------------+---------+------------+----------------------------------------------------------------------------------------------
cube          | 1.5     | public     | data type for multidimensional cubes
earthdistance | 1.1     | public     | calculate great-circle distances on the surface of the Earth
plpgsql       | 1.0     | pg_catalog | PL/pgSQL procedural language
uuid-ossp     | 1.1     | public     | generate universally unique identifiers (UUIDs)
vectors       | 0.2.1   | vectors    | vectors: Vector database plugin for Postgres, written in Rust, specifically designed for LLM
(5 rows)

immich=# reindex database;
REINDEX
```

Immich server restarted OK after that.

**Comment by cutecutecat** [comment]
Thanks for your response, we have seen it's not very clear for upgrading to `v0.2.1`.

We will add the step to `REINDEX` at our upgrading docs soon.

**Comment by YowFung** [comment]
Hi, @reefland 

I try `reindex database;` but it show me an error.

```log
immich=# reindex database;
ERROR:  syntax error at or near ";"
LINE 1: reindex database;
                        ^
immich=# 
```
```log
2025-02-11 20:07:21.702 CST [1731] ERROR:  syntax error at or near ";" at character 17
2025-02-11 20:07:21.702 CST [1731] STATEMENT:  reindex database;
```
